extends SceneTree

## Builds SpriteFrames for the effect sheets added by the eleven-sheet package:
## the three Convergence signatures, the rally target marker, and the Spirit Core
## objective states.
##
##   godot --headless --path . --script scripts/tools/build_effect_spriteframes.gd
##
## Also writes a ground-pivot audit to docs/generated/effect_metrics.json, the
## same gate the actor builders use. Do not hand-edit the generated .tres.

const METRICS := "res://docs/generated/effect_metrics.json"

## Two layouts appear here.
##
## `fx_columns > 0` means the row is one animation of N frames named
## `fx_01..fx_NN` — a single effect playing out over time.
##
## A non-empty `columns` array instead means the cells are unrelated *states*,
## so each becomes its own single-frame animation.
const SETS := [
	{
		"out": "res://data/vfx/convergence_frames.tres",
		"dir": "res://assets/vfx/convergence_frames",
		"rows": ["lightning_wolf", "circular_blade_cut", "multi_cannon_barrage"],
		"columns": [],
		"fx_columns": 8,
		"loop": false,
		# Matches the existing combat VFX atlas rate.
		"fps": 16.0,
	},
	{
		"out": "res://data/vfx/rally_marker_frames.tres",
		"dir": "res://assets/vfx/rally_marker_frames",
		"rows": ["rally_marker"],
		"columns": [],
		"fx_columns": 6,
		# The package validates that frame 6 flows back into frame 1, so this
		# is a true loop rather than a one-shot.
		"loop": true,
		# ANIMATION_GUIDE §3 base rate; 6 frames gives a 0.5 s pulse.
		"fps": 12.0,
	},
	{
		"out": "res://data/environment/spirit_core_frames.tres",
		"dir": "res://assets/environment/spirit_core_frames",
		"rows": ["spirit_core"],
		"columns": ["intact", "damaged", "destroyed"],
		"fx_columns": 0,
		"loop": false,
		# Damage states hold until the objective changes; the rate never applies.
		"fps": 1.0,
	},
]


func _initialize() -> void:
	var missing: Array[String] = []
	var metrics: Dictionary = {}

	for spec in SETS:
		var out_path: String = spec["out"]
		var frame_dir: String = spec["dir"]
		var rows: Array = spec["rows"]
		var columns: Array = spec["columns"]
		var fx_columns: int = spec["fx_columns"]

		if not DirAccess.dir_exists_absolute(frame_dir):
			print("%s: art not present, skipped" % frame_dir.get_file())
			continue

		var frames := SpriteFrames.new()
		frames.remove_animation("default")
		var set_metrics: Dictionary = {}

		for row in rows.size():
			var row_name: String = rows[row]

			if fx_columns > 0:
				var paths: Array[String] = []
				for col in fx_columns:
					paths.append("%s/%02d_%s__%02d_fx_%02d.png" % [frame_dir, row, row_name, col, col + 1])
				var m := _add_animation(frames, row_name, paths, bool(spec["loop"]), float(spec["fps"]), missing)
				if not m.is_empty():
					set_metrics[row_name] = m
			else:
				for col in columns.size():
					var col_name: String = columns[col]
					var path := "%s/%02d_%s__%02d_%s.png" % [frame_dir, row, row_name, col, col_name]
					var m := _add_animation(frames, col_name, [path], bool(spec["loop"]), float(spec["fps"]), missing)
					if not m.is_empty():
						set_metrics[col_name] = m

		if frames.get_animation_names().is_empty():
			continue

		DirAccess.make_dir_recursive_absolute(out_path.get_base_dir())
		var err := ResourceSaver.save(frames, out_path)
		if err != OK:
			print("FAILED: save %s (err %d)" % [out_path, err])
			quit(1)
			return

		metrics[out_path.get_file()] = set_metrics
		print("Built %s" % out_path)
		for name in frames.get_animation_names():
			var m: Dictionary = set_metrics.get(name, {})
			print("  %-22s %d frames  spread=%dpx" % [
				name, frames.get_frame_count(name), int(m.get("baseline_spread_px", 0)),
			])

	if not missing.is_empty():
		push_error("Missing %d effect frames: %s" % [missing.size(), ", ".join(missing)])
		print("FAILED: %d missing" % missing.size())
		quit(1)
		return

	DirAccess.make_dir_recursive_absolute("res://docs/generated")
	var f := FileAccess.open(METRICS, FileAccess.WRITE)
	if f != null:
		f.store_string(JSON.stringify({
			"_note": "Generated by scripts/tools/build_effect_spriteframes.gd. baseline_spread_px is the drift of the lowest opaque row across an animation; 0 means every frame shares a ground line.",
			"sets": metrics,
		}, "  "))
		f.close()
	print("Wrote %s" % METRICS)
	quit(0)


## Adds one animation and returns its pivot audit, or {} if nothing loaded.
func _add_animation(
	frames: SpriteFrames,
	name: String,
	paths: Array,
	loop: bool,
	fps: float,
	missing: Array[String],
) -> Dictionary:
	var foot_rows: Array[int] = []
	var added := 0

	for path in paths:
		var p: String = path
		if not ResourceLoader.exists(p):
			missing.append(p.get_file())
			continue
		var tex := load(p) as Texture2D
		if tex == null:
			missing.append(p.get_file())
			continue
		if added == 0:
			frames.add_animation(name)
			frames.set_animation_loop(name, loop)
			frames.set_animation_speed(name, fps)
		frames.add_frame(name, tex)
		added += 1

		var foot := _foot_row(tex)
		if foot >= 0:
			foot_rows.append(foot)

	if added == 0:
		return {}

	var spread := 0
	if not foot_rows.is_empty():
		foot_rows.sort()
		spread = foot_rows[foot_rows.size() - 1] - foot_rows[0]

	return {
		"frame_count": added,
		"baseline_foot_rows": foot_rows,
		"baseline_spread_px": spread,
	}


## Lowest row holding a visible pixel, or -1 when the frame is empty.
func _foot_row(tex: Texture2D) -> int:
	var img := tex.get_image()
	if img == null:
		return -1
	for y in range(img.get_height() - 1, -1, -1):
		for x in img.get_width():
			if img.get_pixel(x, y).a > 0.02:
				return y
	return -1
